#!/usr/bin/env bash

DIR=$(cd $(dirname $0); pwd)
TIMEOUT=10

print_help()
{
cat <<EndOfMessage
Usage: deploy [-c] [-d] [-s]

Options:
  c : deploy controller
  d : deploy driver
  s : deploy servers
EndOfMessage
}

deploy_controller()
{
  echo -e "\033[1m**** Deploying Controller to nsl002 ****\033[0m"
  local jar="$DIR/floodlight/target/floodlight.jar"
  local props="$DIR/controller/src/main/resources/floodlightloadbalancer.properties"
  scp -o ConnectTimeout=$TIMEOUT $jar $props nsl002:~
  echo
}

deploy_driver()
{
  echo -e "\033[1m**** Deploying Driver to nsl200 ****\033[0m"
  local jar="$DIR/driver/target/driver.jar"
  scp -o ConnectTimeout=$TIMEOUT $jar nsl200:~
  echo
}

deploy_server()
{
  local jar="$DIR/server/target/server.jar"
  for i in $(seq 3 6); do
    nsl="nsl$(printf %03d $i)"
    echo -e "\033[1m**** Deploying Server to $nsl ****\033[0m"
    scp -o ConnectTimeout=$TIMEOUT $jar $nsl:~
    echo
  done
}

# Parse args
RAN_SOMETHING=0
while getopts cdsh name; do
  case $name in
    c) deploy_controller; RAN_SOMETHING=1;;
    d) deploy_driver; RAN_SOMETHING=1;;
    s) deploy_server; RAN_SOMETHING=1;;
    h) print_help; exit 1;;
  esac
done

# Print help if no args
if [[ $RAN_SOMETHING == 0 ]]; then
    print_help
    exit 1
fi
