#!/usr/bin/env bash

ovs-ofctl del-flows br1
ovs-ofctl add-flow br1 ip,nw_dst=10.1.1.2,actions=output:1
ovs-ofctl add-flow br1 ip,nw_dst=10.1.1.3,actions=output:2
ovs-ofctl add-flow br1 ip,nw_src=10.1.1.2,nw_dst=10.0.0.0/8,actions=output:4
ovs-ofctl add-flow br1 ip,nw_src=10.1.1.3,nw_dst=10.0.0.0/8,actions=output:4
